### ISSUE TITLE
Android app crashes when starting/receiving a call (APK file)

### ISSUE THREAD

**Issue by helene-bieber** [twilio/twilio-voice-react-native#148]
The calls are working as intended during testing with Android Studio but when deploying the app and installing it with an APK file on my phone then the app crashes as soon as I start the call.

**Comment by helene-bieber** [comment]
Sure, it looks like I get an error:

`    --------- beginning of crash
2023-03-08 09:48:51.502 19213-19213/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.helene1245.test, PID: 19213
    java.lang.RuntimeException: Unable to start service com.twiliovoicereactnative.IncomingCallNotificationService@c15d616 with Intent { act=ACTION_OUTGOING_CALL cmp=com.helene1245.test/com.twiliovoicereactnative.IncomingCallNotificationService (has extras) }: java.lang.IllegalArgumentException: com.helene1245.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4673)
        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2180)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.IllegalArgumentException: com.helene1245.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
        at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:750)
        at android.app.PendingIntent.getService(PendingIntent.java:712)
        at com.twiliovoicereactnative.NotificationUtility.createOutgoingCallNotificationWithLowImportance(NotificationUtility.java:190)
        at com.twiliovoicereactnative.IncomingCallNotificationService.handleOutgoingCall(IncomingCallNotificationService.java:137)
        at com.twiliovoicereactnative.IncomingCallNotificationService.onStartCommand(IncomingCallNotificationService.java:69)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4655)
        	... 9 more`

**Comment by mhuynh5757** [comment]
Hi @helene-bieber, thanks for reaching out. Please try out the new beta release of the SDK. This issue may have been addressed.

**Comment by helene-bieber** [comment]
That worked! Thank you!

**Comment by umairm1alik** [comment]
I am implementing auto accept call on call receive the moment it accepted  automatically my crashes and i am receiving this error in the log cat

` E  FATAL EXCEPTION: mqt_native_modules
                                                                                                    Process: com.intelytics, PID: 8619
                                                                                                    java.lang.NullPointerException
                                                                                                    	at java.util.Objects.requireNonNull(Objects.java:207)
                                                                                                    	at com.twiliovoicereactnative.CallListenerProxy.onConnected(CallListenerProxy.java:99)
                                                                                                    	at com.twilio.voice.Call$1.lambda$onConnected$1$com-twilio-voice-Call$1(Call.java:680)
                                                                                                    	at com.twilio.voice.Call$1$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`

**Comment by umairm1alik** [comment]
Also auto accept is working fine in debug mode but crashing in release mode
