### ISSUE TITLE
Android - Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent 

### ISSUE THREAD

**Issue by omerts** [twilio/twilio-voice-react-native#176]
Hello,

Gettting the following exception in Android:
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.HEADSET_PLUG flg=0x40000010 (has extras) } in com.twilio.audioswitch.wired.WiredHeadsetReceiver@878e55b
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1815)
       at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
       
**Device**
Brand:Samsung
Model:Galaxy A23
Orientation:Portrait
RAM free: 1.13 GB
Disk free: 48.61 GB
Operating system
Version:Android 12
Orientation:Portrait
Rooted:No

**Comment by afalls-twilio** [comment]
@omerts thanks for reporting the issue, can you please provide more information on what the user was doing or what the application was doing at the time of this event?  Also, were you able to reproduce this with the quickstart?

**Comment by kbagchiGWC** [comment]
Closing due to inactivity. Please open a new ticket if you need help.
