### ISSUE TITLE
Android: outbound calls make the app crash - beta 3

### ISSUE THREAD

**Issue by liemdo** [twilio/twilio-voice-react-native#212]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
When I make an outbound call, it goes through but the app crashes immediately. This happens in 1.0.0-beta3. The app works fine with 1.0.0-beta2

## Reproduction Steps
1. Make outbound calls
2. Observe that the app crashes with the error
```
java.lang.RuntimeException: Unable to start service com.twiliovoicereactnative.IncomingCallNotificationService@31c36f4 with Intent { act=ACTION_OUTGOING_CALL cmp=com.ringblaze.app/com.twiliovoicereactnative.IncomingCallNotificationService (has extras) }: java.lang.IllegalArgumentException: foregroundServiceType 0x00000080 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4657)
        at android.app.ActivityThread.access$2000(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: foregroundServiceType 0x00000080 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2429)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7096)
        at android.app.Service.startForeground(Service.java:786)
        at com.twiliovoicereactnative.IncomingCallNotificationService.startForegroundCompat(IncomingCallNotificationService.java:180)
        at com.twiliovoicereactnative.IncomingCallNotificationService.handleOutgoingCall(IncomingCallNotificationService.java:158)
        at com.twiliovoicereactnative.IncomingCallNotificationService.onStartCommand(IncomingCallNotificationService.java:71)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4639)
        ... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1723)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1350)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:11892)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3205)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2498)
```

## Software and Device Information
**Please complete the following information.**
 - Device: [e.g. iPhone 12, Pixel 3] Pixel 4
 - OS: [e.g. iOS 16, Android API Level 31]: Android 12
 - React version: [e.g. 18.1.0] 18.2.0
 - React Native version: [e.g. 0.70.9] 0.71.8
 - Node version: [e.g. 16.18.1] 18
 - npm or yarn version: [e.g. 8.19.2, 1.22.19] pnpm 7

**Comment by mhuynh5757** [comment]
Hi @liemdo sorry for the delayed response. Please see this file for declaring the required services for the Android app to function properly, you may be missing one or more these in your manifest files.

https://github.com/twilio/twilio-voice-react-native/blob/main/test/app/android/app/src/main/AndroidManifest.xml
