### ISSUE TITLE
In Android app is getting crashed when incoming call is accepted from Notification Button

### ISSUE THREAD

**Issue by ankitCompunnel** [twilio/twilio-voice-react-native#401]
#  In Android app is getting crashed when incoming call is accepted from Notification Button

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
When accepting the incoming call from notification accept button my app is crashing . While debugging in my android studio in my logcate I found the below error when app get's crashed when incoming call is accepted from notification banner.

FATAL EXCEPTION: main
                                                                                                    Process: com.callingapp, PID: 9959
                                                                                                    java.lang.NullPointerException
                                                                                                    	at java.util.Objects.requireNonNull(Objects.java:220)
                                                                                                    	at com.twiliovoicereactnative.CallListenerProxy.onConnected(CallListenerProxy.java:99)
                                                                                                    	at com.twilio.voice.Call$1.lambda$onConnected$1$com-twilio-voice-Call$1(Call.java:680)
                                                                                                    	at com.twilio.voice.Call$1$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

## Expected Behavior
Trying to accept the call from default notification accept button .

## Actual Behavior
App is getting crashed when call is accepted from default notification accept button 

## Reproduction Frequency
I am using the sdk for last 25 days for testing and development . Initially app was not crashing but last 2 days it is getting crashed.

## Software and Device Information
**Please complete the following information.**
 - Device: Pixel 3A
 - OS:  Android API Level 33
 - React version: ^18.2.0
 - React Native version: 0.74.3
 - Node version: v20.15.1
 - npm or yarn version: 10.8.2

**Comment by afalls-twilio** [comment]
@ankitCompunnel can you place a break point here and validate that this is where the crash is happening?
https://github.com/twilio/twilio-voice-react-native/blob/adea38cf1fa2ab6207bf9bf7807e064038dd9e86/android/src/main/java/com/twiliovoicereactnative/CallListenerProxy.java#L99

**Comment by traxx10** [comment]
Could you confirm if you have notifications enabled for mic?

**Comment by mhuynh5757** [comment]
Hi @traxx10 thanks for helping out in the community. Could I ask you for more details? We'd like to avoid crashes, even if permissions are not set properly. I'm not sure what you mean by "notifications enabled for mic", do you mean permissions for microphone access and permissions for showing notifications?

**Comment by traxx10** [comment]
Hello @mhuynh5757 yes. Permissions for mic. Some of my app users were constantly disabling the mic permissions which resulted in a crash. What I did was to disable registering voice token unless the user explicitly accepted the mic permissions

**Comment by mhuynh5757** [comment]
Hey @traxx10 please check out the new release `1.1.0`, this should address the crashing issues on Android when permissions are not granted.

**Comment by mhuynh5757** [comment]
This should also address the original issue @ankitCompunnel, please try the new version. I will close this issue for now, but please reach out again if you continue to have issues on the latest version.
